apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aws-account-operator
  name: aws-account-shredder
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - 'get'
  - 'list'
- apiGroups:
    - aws.managed.openshift.io
  resources:
    - accounts
    - accounts/status
  verbs:
    - 'get'
    - 'list'
    - 'update'
