apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aws-account-shredder
  namespace: aws-account-operator
subjects:
- kind: ServiceAccount
  name: aws-account-shredder
  namespace: aws-account-operator
roleRef:
  kind: Role
  name: aws-account-shredder
  apiGroup: rbac.authorization.k8s.io
  namespace: aws-account-operator
